GET http://127.0.0.1:8000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDQzNjgxLCJpYXQiOjE3NjU0NDMzODEsImp0aSI6ImNlOTQ4MjUxOGNjODQ2OTZhMjNmZGVkODk1OGNjZWRiIiwidXNlcl9pZCI6IjEifQ.eVoLo5w-60p680kTFksEv2oPaQZ3CPvqOeZu9OMwwBA