GET http://127.0.0.1:8000/api/notes?page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxMDQwNjE0MDM3NSwiaWF0IjoxNzY2MjI2Nzc1LCJqdGkiOiI5OWZlYjVkMWY0NzQ0Y2ZmYjA4NDZjNDFlNTEyMzNmYyIsInVzZXJfaWQiOiIxIn0.8z2_3bqM7oWfPUkyfbjE89g_1rzZ7__ZL8WbM-a-O00
